apiVersion: v1alpha1
kind: Setting
metadata:
  name: s3os-settings
spec:
  forms: 
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: text
          help: 请前往 “附件 - 存储策略” 添加策略
          label: 此处不用设置，请前往 “附件 - 存储策略” 添加策略
          name: text
          placeholder: 此处不用设置，请前往 “附件 - 存储策略” 添加策略
